/* eslint-disable import/no-anonymous-default-export */

enum ART_TYPE {
	PAINTING =  "PAINTING",
	MEDIA = "INTERACTIVE",
	SCULPTURE = "SCULPTURE",
};

enum DEPARTMENTS {
    AFRICAN_ART = "AFRICAN_ART",
    AMERICAN_WING = "AMERICAN_WING",
    ANCIENT_NEAR_EASTERN_ART = "ANCIENT_NEAR_EASTERN_ART",
    ARMS_AND_ARMOR = "ARMS_AND_ARMOR",
    ANCIENT_AMERICAN_ART = "ANCIENT_AMERICAN_ART",
    ASIAN_ART = "ASIAN_ART",
    COSTUME_INSTITUTE = "COSTUME_INSTITUTE",
    DRAWINGS_AND_PRINTS = "DRAWINGS_AND_PRINTS",
    EGYPTIAN_ART = "EGYPTIAN_ART",
};


enum STATUS {
    PENDING = 'PENDING',
    SUCCESS = 'SUCCESS',
    FAILURE = 'FAILURE',
};

enum DB_TITLE {
    FLOWER_GIRL = "FLOWER_GIRL",
    SEASIDE = "SEA_SIDE",
    MADAME_X = "MADAME_X",
    DRAGONS_FLOWERS = "DRAGONS_FLOWERS",
    NIGHT_RAIN = "NIGHT_RAIN",
    VIRGIN_FACING_RIGHT = "VIRGIN_FACING_RIGHT",
    RELIEF_MENTUHOTEP = "RELIEF_MENTUHOTEP",
    WOMAN_MAN_CASEMENT = "WOMAN_MAN_CASEMEN",
    WHEAT_FIELD = "WHEAT_FIELD",
    HARVESTERS = "HARVESTERS",
    MUSICIANS = "MUSICIANS",
    WAVY_VINE = "WAVY_VINE",
    PORT_BOULOGNE = "PORT_BOULOGNE"
};


export default {
    ART_TYPE,
	DEPARTMENTS,
    DB_TITLE,
    STATUS,
}
