/* eslint-disable import/no-anonymous-default-export */

enum ART_TYPE {
	PAINTING =  "PAINTING",
	MEDIA = "INTERACTIVE",
	SCULPTURE = "SCULPTURE",
};

enum DEPARTMENTS {
    AFRICAN_ART = "AFRICAN_ART",
    AMERICAN_WING = "AMERICAN_WING",
    ANCIENT_NEAR_EASTERN_ART = "ANCIENT_NEAR_EASTERN_ART",
    ARMS_AND_ARMOR = "ARMS_AND_ARMOR",
    ANCIENT_AMERICAN_ART = "ANCIENT_AMERICAN_ART",
    ASIAN_ART = "ASIAN_ART",
    COSTUME_INSTITUTE = "COSTUME_INSTITUTE",
    DRAWINGS_AND_PRINTS = "DRAWINGS_AND_PRINTS",
    EGYPTIAN_ART = "EGYPTIAN_ART",
};

export default {
    ART_TYPE,
	DEPARTMENTS,
}
