import { Artwork } from '../utils/apiModels'
import enums from '../utils/enums';

import madameX from  './madamex.jpeg';
/*
TEMPLATE:
  {
        metId: ``,
        department: ``,
        imgSrc: ``,
        title: ``,
        date: ``,
        creator: ``,
        creatorNationality: ``,
        placeOfOrigin: null,
        metLocation: ``,
        description: ``,
        artworkDetails: {
        },
    },
*/

export const OBJECT_DATA = [
    {
        metId: 10464,
        dbTitle: enums. DB_TITLE.SEASIDE,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/10464/32489/main-image`,
        title: `At the Seaside`,
        date: `ca 1982`,
        creator: `William Meritt Chase`,
        creatorNationality: `American`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 769`,
        description: `From 1891 to 1902, Chase served as the director of the Shinnecock Hills Summer School of Art in the town of Southampton, on Long Island, New York. Chase taught two days each week and spent the rest of his time painting and enjoying the company of his family. In this canvas, women and children take their ease on a beach, probably along Shinnecock Bay. A perfect site for genteel leisure on a perfect day, Chase’s rendering is capped by a broad expanse of sky that fills the upper half of the canvas. The scudding clouds artfully echo the bright white forms of the children’s dresses and the parasol.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 39733,
        dbTitle: enums. DB_TITLE.DRAGONS_FLOWERS,
        department: enums.DEPARTMENTS.ANCIENT_NEAR_EASTERN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/39733/147899/main-image`,
        title: `Tapestry with Dragons and Flowers`,
        date: `11-12th Century`,
        creator: `Eastern Central Asia`,
        creatorNationality: null,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 241`,
        description: `The decorative style of this silk tapestry is typical of Central Asia, where motifs enjoyed great longevity and creative recombination. The form of the dragon, with its long snout and its tail hooked behind its leg, represents a Tang-dynasty convention that survived in Central Asia until at least the Yuan dynasty, founded in 1271 by the Mongol conqueror Khubilai Khan. Placing a dragon on flowers is most likely a Central Asian invention. The brilliant colors and the vitality of the animals are also characteristic features of tapestries of the region, which were probably produced by Uighurs, known for their splendid tapestry-woven clothing.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 37145,
        dbTitle: enums. DB_TITLE.NIGHT_RAIN,
        department: enums.DEPARTMENTS.ASIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/37145/140252/main-image`,
        title: `Night Rain at the Double-Shelf Stand, from the series Eight Parlor Views (Zashiki hakkei)`,
        date: `11-12th Century`,
        creator: `Suzuki Harunobu`,
        creatorNationality: 'Japanese',
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 241`,
        description: `This beguiling scene of a girl lulled by the sound of a softly boiling tea cauldron, set on a portable hearth of the type used during the summer, is one of Harunobu’s Eight Parlor Views (Zashiki hakkei). It playfully alludes to “Night Rain,” one of the Eight Views of the Xiao and Xiang Rivers in China, a venerable theme in both Chinese and Japanese painting. Here the summer mood intrinsic to that landscape is transposed to the interior of an Edo (Tokyo) house of pleasure. Harunobu’s work is distinctive for its subtle tonality, achieved by mixing pigments rather than by superimposing two printed colors.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 337496,
        dbTitle: enums. DB_TITLE.VIRGIN_FACING_RIGHT,
        department: enums.DEPARTMENTS.ANCIENT_NEAR_EASTERN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/337496/739534/main-image`,
        title: `The Head of the Virgin in Three-Quarter View Facing Right`,
        date: `1510-1513`,
        creator: `Leonardo Da Vinci`,
        creatorNationality: 'Italian',
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 400`,
        description: `Fully revealed in 2005, the verso of this sheet is inscribed with a gray-brown ink ".T." that is quite reminiscent of the "Melzi-Leoni" markings on Leonardo’s drawings and manuscripts. The study for the head of the Virgin on the recto has sometimes been doubted by scholars 'ex silentio' as being by Leonardo, possibly because its magical beauty renders it suspicious (Walter Vitzthum in 1966 quoted a recent English critic’s opinion in his support, "the drawing makes one think of Walter Pater’s mind rather than of Leonardo’s hand"). However, even in Leonardo’s most densely pictorial drawings, a few traces of his left-handed parallel hatching often remain visible underneath all the layers of the worked up medium. As the detailed scientific analyses of 2002-2003 demonstrated, this drawing is done with a nearly seamless sfumato technique, and is extremely homogeneous in its dense use of red and black chalks, revealing extensive, unified left-handed strokes in the rubbed-in intermediate shadows; these lines are also partly evident with the plain, unassisted eye (laboratory examinations by Marjorie Shelley and Rachel Mustalish, Paper Conservators, The Metropolitan Museum of Art; microphotograph details published and discussed by Carmen C. Bambach in Metropolitan Museum of Art 2003, pp. 41-42, 46-47, figs. 35a-d).`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 548212,
        dbTitle: enums. DB_TITLE.RELIEF_MENTUHOTEP,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/548212/1348549/main-image`,
        title: `Relief of Nebhepetre Mentuhotep II and the Goddess Hathor`,
        date: `ca. 2010-2000 B.C.`,
        creator: `Middle Kingdom`,
        creatorNationality: null,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 104`,
        description: `King Nebhepetre Mentuhotep II was revered by the Egyptians as the ruler who reunited Egypt after the era of disunity (the First Intermediate Period) that followed the end of the Old Kingdom. Descended from a family of Theban rulers, the king built his tomb and mortuary temple at Deir el-Bahri in western Thebes. This relief was originally part of the decoration of the temple's main sanctuary that was added to the building at the end of the king's reign. The fine balance between figures and inscriptions on this block, as well as the clear outline and regular proportions of the king's image with its individualized facial features, exemplify the peak of a relief art that had developed over the decades while the vast temple complex was built and decorated. The figure of the goddess Hathor on the right of the block was chiselled away during the Amarna period, when King Akhenaten propagated the sole worship of the god Aten. Hathor was repaired in plaster in early Dynasty 19 and some of the paint on the whole block may also have been renewed at the time.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 436896,
        dbTitle: enums. DB_TITLE.WOMAN_MAN_CASEMENT,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/436896/795014/main-image`,
        title: `Portrait of a Woman with a Man at a Casement`,
        date: `ca. 1440`,
        creator: `Fra Filippo Lippi`,
        creatorNationality: `Italian`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 602`,
        description: `This is the earliest surviving double portrait in Italy, the first to show the sitters in a domestic setting, and the first with a view onto a landscape. The woman, dressed luxuriously ala francese, her sleeve embroidered with letters spelling "lealta" (faithful), is observed by a man—her betrothed?—appearing at a window, his hands on an identifying coat of arms. The two figures may be Lorenzo di Ranieri Scolari and Angiola di Bernardo Sapiti, who were married about 1439. Lippi’s task was complicated by the Italian preference for the profile view as opposed to the three-quarter view preferred north of the Alps.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 436535,
        dbTitle: enums. DB_TITLE.WHEAT_FIELD,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/436535/796067/main-image`,
        title: `Wheat Field with Cypresses`,
        date: `1889`,
        creator: `Vincent Van Gogh`,
        creatorNationality: `Dutch`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 822`,
        description: `Cypresses gained ground in Van Gogh’s work by late June 1889 when he resolved to devote one of his first series in Saint-Rémy to the towering trees. Distinctive for their rich impasto, his exuberant on-the-spot studies include the Met’s close-up vertical view of cypresses (49.30) and this majestic horizontal composition, which he illustrated in reed-pen drawings sent to his brother on July 2. Van Gogh regarded the present work as one of his “best” summer landscapes and was prompted that September to make two studio renditions: one on the same scale (National Gallery, London) and the other a smaller replica, intended as a gift for his mother and sister (private collection).`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 435809,
        dbTitle: enums. DB_TITLE.HARVESTERS,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/435809/794356/main-image`,
        title: `The Harvesters`,
        date: `1565`,
        creator: `Pieter Bruegel the Elder`,
        creatorNationality: `Netherlandish`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 625`,
        description: `In this work, the viewer is transported to a hot summer day in the Netherlands. It belongs to a series, commissioned by the Antwerp merchant Niclaes Jongelinck for his suburban home. The cycle originally included six paintings showing the times of the year. Apart from The Harvesters, which is usually identified as representing July–August, four other paintings of the group have survived (now in the Kunsthistorisches Museum, Vienna, and Lobkowicz Collection, Prague). Bruegel’s series is a watershed in the history of Western art. The religious pretext for landscape painting has been suppressed in favor of a new humanism, and the unidealized description of the local scene is based on natural observations.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 435844,
        dbTitle: enums. DB_TITLE.MUSICIANS,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/435844/1581937/main-image`,
        title: `The Musicians`,
        date: `1597`,
        creator: `Caravaggio (Michelangelo Merisi)`,
        creatorNationality: `Italian`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 288`,
        description: `While Cupid confirms Caravaggio’s allegorical frame for representing Music, the artist equally engages with contemporary performance and individualized models, including a self-portrait in the second boy from the right. Caravaggio’s contemporary, Giovanni Baglione, recorded that the artist painted "a concert, with some youths portrayed from nature very well" immediately after joining the household of his first great patron, Cardinal Francesco Maria del Monte. Most likely, this is the same painting and is one of several employing the half-length, earthy yet sensual figures with which Caravaggio made his name upon arriving in Rome.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 451101,
        dbTitle: enums. DB_TITLE.WAVY_VINE,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/451101/903033/main-image`,
        title: `Fragmentary Loom Width with Wavy-Vine Pattern`,
        date: `ca. 1565-1580`,
        creator: null,
        creatorNationality: null,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 920`,
        description: `Spectacular, large‑pattern silks were favored materials for luxury garments among the courtly elite of sixteenth-century Istanbul, and were often used for the bold, richly colored caftans of the Ottoman sultans. The weave here, referred to in Turkish as kemha, incorporates metal‑wrapped thread into a lampas, or multiweave fabric. Ottoman kemha fabrics typically combine a satin ground with a design executed in twill and highlighted with gold. Catching the light, their glittering patterns appear to float above a shimmering background.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 266644,
        dbTitle: enums. DB_TITLE.PORT_BOULOGNE,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/266644/608585/main-image`,
        title: `[Entrance to the Port of Boulogne]`,
        date: `1855`,
        creator: `Edouard Baldus`,
        creatorNationality: `French, born Prussia`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 103`,
        description: `Boulogne-sur-Mer, the terminus of the railroad line from Paris, was the gateway for trade and travel between Victorian England and Second Empire France. It was also the arrival point for Queen Victoria's state visit in 1855, and this exceptionally rich, subtle print comes from an album commissioned by Baron James de Rothschild, owner of the line, for presentation to the imperial court on that occasion. Baldus's photograph, showing the elegantly engineered jetties that guided vessels from the English Channel past the scruffy shoreline and into the protected harbor alongside the Boulogne station, masterfully renders the soft light and atmosphere pursued by Impressionist painters a decade later.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 11207,
        dbTitle: enums. DB_TITLE.FLOWER_GIRL,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://images.metmuseum.org/CRDImages/ad/original/DT2784.jpg`,
        title: `The Flower Girl`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 12127,
        dbTitle: enums. DB_TITLE.MADAME_X,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: madameX,
        title: `Madame X (Madame Pierre Gautreau)`,
        date: `1883-84`,
        creator: `John Singer Sargent`,
        creatorNationality: `American`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 771`,
        description: `
        Madame Pierre Gautreau (the Louisiana-born Virginie Amélie Avegno; 1859–1915) was known in Paris for her artful appearance. Sargent hoped to enhance his reputation by painting and exhibiting her portrait. Working without a commission but with his sitter’s complicity, he emphasized her daring personal style, showing the right strap of her gown slipping from her shoulder. At the Salon of 1884, the portrait received more ridicule than praise. Sargent repainted the shoulder strap and kept the work for over thirty years. When, eventually, he sold it to the Metropolitan, he commented, “I suppose it is the best thing I have done,” but asked that the Museum disguise the sitter’s name.
        `,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
];

//For later: add more details
