import { Artwork } from '../utils/apiModels'
import enums from '../utils/enums';

import madameX from  './madamex.jpeg';
/*
TEMPLATE:
  {
        metId: ``,
        department: ``,
        imgSrc: ``,
        title: ``,
        date: ``,
        creator: ``,
        creatorNationality: ``,
        placeOfOrigin: null,
        metLocation: ``,
        description: ``,
        artworkDetails: {
        },
    },
*/

export const OBJECT_DATA = [
    {
        metId: 10464,
        dbTitle: enums. DB_TITLE.SEASIDE,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/10464/32489/main-image`,
        title: `At the Seaside`,
        date: `ca 1982`,
        creator: `William Meritt Chase`,
        creatorNationality: `American`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 769`,
        description: `From 1891 to 1902, Chase served as the director of the Shinnecock Hills Summer School of Art in the town of Southampton, on Long Island, New York. Chase taught two days each week and spent the rest of his time painting and enjoying the company of his family. In this canvas, women and children take their ease on a beach, probably along Shinnecock Bay. A perfect site for genteel leisure on a perfect day, Chase’s rendering is capped by a broad expanse of sky that fills the upper half of the canvas. The scudding clouds artfully echo the bright white forms of the children’s dresses and the parasol.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 39733,
        dbTitle: enums. DB_TITLE.DRAGONS_FLOWERS,
        department: enums.DEPARTMENTS.ANCIENT_NEAR_EASTERN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/39733/147899/main-image`,
        title: `Tapestry with Dragons and Flowers`,
        date: `11-12th Century`,
        creator: `Eastern Central Asia`,
        creatorNationality: null,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 241`,
        description: `The decorative style of this silk tapestry is typical of Central Asia, where motifs enjoyed great longevity and creative recombination. The form of the dragon, with its long snout and its tail hooked behind its leg, represents a Tang-dynasty convention that survived in Central Asia until at least the Yuan dynasty, founded in 1271 by the Mongol conqueror Khubilai Khan. Placing a dragon on flowers is most likely a Central Asian invention. The brilliant colors and the vitality of the animals are also characteristic features of tapestries of the region, which were probably produced by Uighurs, known for their splendid tapestry-woven clothing.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 37145,
        dbTitle: enums. DB_TITLE.NIGHT_RAIN,
        department: enums.DEPARTMENTS.ANCIENT_NEAR_EASTERN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/37145/140252/main-image`,
        title: `Night Rain at the Double-Shelf Stand, from the series Eight Parlor Views (Zashiki hakkei)`,
        date: `11-12th Century`,
        creator: `Suzuki Harunobu`,
        creatorNationality: 'Japanese',
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 241`,
        description: `The decorative style of this silk tapestry is typical of Central Asia, where motifs enjoyed great longevity and creative recombination. The form of the dragon, with its long snout and its tail hooked behind its leg, represents a Tang-dynasty convention that survived in Central Asia until at least the Yuan dynasty, founded in 1271 by the Mongol conqueror Khubilai Khan. Placing a dragon on flowers is most likely a Central Asian invention. The brilliant colors and the vitality of the animals are also characteristic features of tapestries of the region, which were probably produced by Uighurs, known for their splendid tapestry-woven clothing.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 337496,
        dbTitle: enums. DB_TITLE.VIRGIN_FACING_RIGHT,
        department: enums.DEPARTMENTS.ANCIENT_NEAR_EASTERN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/337496/739534/main-image`,
        title: `The Head of the Virgin in Three-Quarter View Facing Right`,
        date: `11-12th Century`,
        creator: `Suzuki Harunobu`,
        creatorNationality: 'Japanese',
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 241`,
        description: `The decorative style of this silk tapestry is typical of Central Asia, where motifs enjoyed great longevity and creative recombination. The form of the dragon, with its long snout and its tail hooked behind its leg, represents a Tang-dynasty convention that survived in Central Asia until at least the Yuan dynasty, founded in 1271 by the Mongol conqueror Khubilai Khan. Placing a dragon on flowers is most likely a Central Asian invention. The brilliant colors and the vitality of the animals are also characteristic features of tapestries of the region, which were probably produced by Uighurs, known for their splendid tapestry-woven clothing.`,
        artworkDetails: {
            Title: `At the Seaside`,
            Artist: `William Merritt Chase (American, Williamsburg, Indiana 1849–1916 New York)`,
            Date: `ca. 1892`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `20 × 34 in. (50.8 × 86.4 cm)`,
            "Credit Line": `Bequest of Miss Adelaide Milton de Groot (1876-1967), 1967`,
            "Accession Number": '67.187.123',
        },
    },
    {
        metId: 548212,
        dbTitle: enums. DB_TITLE.RELIEF_MENTUHOTEP,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/548212/1348549/main-image`,
        title: `Relief of Nebhepetre Mentuhotep II and the Goddess Hathor`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 436896,
        dbTitle: enums. DB_TITLE.WOMAN_MAN_CASEMENT,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/436896/795014/main-image`,
        title: `Portrait of a Woman with a Man at a Casement`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 436535,
        dbTitle: enums. DB_TITLE.WHEAT_FIELD,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/436535/796067/main-image`,
        title: `Wheat Field with Cypresses`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 435809,
        dbTitle: enums. DB_TITLE.HARVESTERS,
        department: enums.DEPARTMENTS.EGYPTIAN_ART,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/435809/794356/main-image`,
        title: `The Harvesters`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 435844,
        dbTitle: enums. DB_TITLE.MUSICIANS,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/435844/1581937/main-image`,
        title: `The Musicians`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 451101,
        dbTitle: enums. DB_TITLE.WAVY_VINE,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/451101/903033/main-image`,
        title: `Fragmentary Loom Width with Wavy-Vine Pattern`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 266644,
        dbTitle: enums. DB_TITLE.PORT_BOULOGNE,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://collectionapi.metmuseum.org/api/collection/v1/iiif/266644/608585/main-image`,
        title: `[Entrance to the Port of Boulogne]`,
        date: `1855`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },


    {
        metId: 11207,
        dbTitle: enums. DB_TITLE.FLOWER_GIRL,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: `https://images.metmuseum.org/CRDImages/ad/original/DT2784.jpg`,
        title: `The Flower Girl`,
        date: `1846`,
        creator: `Charles Cromwell Ingham`,
        creatorNationality: `American born  Ireland`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 756`,
        description: `
        The Irish-born Ingham was familiar with European depictions of street vendors hawking their wares. The choice of a flower girl as a subject for this work—rather than, for example, a newsboy—reveals the artist’s preference for female models and his passion for painting clearly identifiable flowers with chromatic lushness. The young woman’s plain dress and head covering contrast with her basket holding nearly twenty intensely colored flowers. In her right hand, she offers a potted fuchsia in a gesture emblematic of Flora, the Roman goddess of flowers. The plant itself is symbolic of love.`,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
    {
        metId: 12127,
        dbTitle: enums. DB_TITLE.MADAME_X,
        department: enums.DEPARTMENTS.AMERICAN_WING,
        imgSrc: madameX,
        title: `Madame X (Madame Pierre Gautreau)`,
        date: `1883-84`,
        creator: `John Singer Sargent`,
        creatorNationality: `American`,
        placeOfOrigin: null,
        metLocation: `On View At the Met Fifth Avenue in Gallery 771`,
        description: `
        Madame Pierre Gautreau (the Louisiana-born Virginie Amélie Avegno; 1859–1915) was known in Paris for her artful appearance. Sargent hoped to enhance his reputation by painting and exhibiting her portrait. Working without a commission but with his sitter’s complicity, he emphasized her daring personal style, showing the right strap of her gown slipping from her shoulder. At the Salon of 1884, the portrait received more ridicule than praise. Sargent repainted the shoulder strap and kept the work for over thirty years. When, eventually, he sold it to the Metropolitan, he commented, “I suppose it is the best thing I have done,” but asked that the Museum disguise the sitter’s name.
        `,
        artworkDetails: {
            Title: `The Flower Girl`,
            Artist: `Charles Cromwell Ingham (American (born Ireland), Dublin 1786–1863 New York)`,
            Date: `1846`,
            Culture: `American`,
            Medium: `Oil on canvas`,
            Dimensions: `36 x 28 3/8 in. (91.4 x 72.1 cm)`,
            "Credit Line": `Gift of William Church Osborn, 1902`,
            "Accession Number": '02.71',
        },
    },
];

//For later: add more details
